services:
  - docker

script:
  - docker build -t inseefrlab/inspacy .

deploy:
  skip_cleanup: true
  provider: script
  script:
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push inseefrlab/inspacy
  on:
    branch: master
env:
  global:
  - secure QzLB0pHZotBAgTY2K4REXXdFRmTnsIxeVrCeumq08jqdIc/1vftwIHXgzeHRnYaTwR+Diwh2FYo6/+ywhbQ/MeKi+5lWaCkqdCYKyIiIoq623hrV9tyeMoRKxvG5XDIjgG6UJtdinmOjvbCKYflzLL+IpJk0DkuVOS5bk3LWF0ti9d0N8fIJZrqX62O50bi3eg+/ko9OJGMtthMHnSoQPczm6nMlcuAZxgchN1cdRHdhKmAaByXPpdF+yx9NXeGcb+lj7fm8SmW6IyeHaPGYg4tA0j5HNPZBlqi+lm8iuPSiyUahqoPClVIBOXCNfrylfBS+wfk75GbNwYwtt0IKPdS1GVDWzZE4MRA18gdDHDaFLP7G0URO7ca6aqsyt6uhpFrGLx+IexIDxJTLgGXcyRqZzpBPSxtQyxe3p+jct1PjDJih8aW8HJsPcN9Yj/pPB860BatDPwjYR+OgeFDT10YardTkmSn3dEURrd7YglCH1VsqqlT4LJgQ0mj0QJUaBLUx08bp/+KLyC9ybWui2ZSOn+/fc14SLu48Km/Da/VYBFzgCkUO40ioTNTEeqXA0ddRHphVBJV31nEVmlUaAXnTYr5xmOi7yGjlJ8pRh6E5lDC08wuOmn+hXwgeETkIJpK6Amm205Aq+Puze3pEM1xkIwEPOAnDU8P5ysjO4W8=
  - secure OCKPc2TTaFFEoRJbpnHzHWPhjShKpjs+Y2PhZq3qwVnVefeU48y2Jb4taNvyERC2dlUmoBkUaIXkAXD4c1lxEGWJH1yYRGqZTBTn+4NMP6RDiG4htIO00r49rHV85q9guWYSHVZCf735PjphL5mUB9ey8IspLoRfRQ0QWbU9mFrrqLwI4gRvwT+6/6jOD+IzyI4jh3okgR1ZpilC2dXsYrwoKEQg9Qv9i5uHhjMuY44Blh7HSA6/lztShQPe/Pfmgp2ImRxERZimuLNpHBEKW2w90K4V58eNLQHmXaI1tWuUCTjJyjSQ/KMo3LTm3i4CtsxAFa8ELZHz6i2ibO73YztBMFqrRhWQDKhHBgdoEB1gt6EpFKdfsj96Xyqt3gfgH/37SSNTWr6Izpv/gI9Yaf+ejkI1OczBzYuUwRN866zHLFPtyeUm7/XwvRN+GGW8Vg3NxNUvznzIc7xn7/d7eFEF0bEQpIw7KNDCZcG5WjLOciAg9TPvheixjkr2l33b0hsU706K0ot6EvTtE7KubArXwTPBtksK9ecQkWGWTBwN7WoJhNdSiMh5RRFaM19ECL4qxMWmiVAhpLGwdVVsRfy+5t9d4T56Quq4gpRJ3IAyCJlmjl35o50v4MiCu8x15OW2gzgkW9YzQS6uxbqBzL6Y/A3ls9pAL1R6jzfWLAg=